
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend_production_machine
    container_name: documentqa_backend_container
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - docqa_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend_production_machine
    container_name: documentqa_frontend_container
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - docqa_network

networks:
  docqa_network:
    driver: bridge
