
# Base image with Python 3.12
FROM python:3.12-slim

# Set work directory inside container
WORKDIR /app

# Copy only requirements first to leverage Docker cache
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Copy full project into container
COPY . .

# Expose FastAPI port
EXPOSE 8080

# Default command to run FastAPI app
CMD ["python", "frontend/main_ui.py"]